name: Deploy Spring Boot Backend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/launchpad-backend .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/launchpad-backend

      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/launchpad-backend
            docker stop logistics-backend || true
            docker rm logistics-backend || true
            docker rmi $(docker images -q ${{ secrets.DOCKERHUB_USERNAME }}/launchpad-backend) || true
            docker run -d \
                  --restart unless-stopped \
                  -p 8080:8080 \
                  --name logistics-backend \
                  -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
                  -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
                  -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
                  ${{ secrets.DOCKERHUB_USERNAME }}/launchpad-backend
